### PR TITLE
Makes it so the credits reflect what the King Zora gives!

### PR DESCRIPTION
**Pull request by mrjnumber1**
a little silly, and a little messy, but i figured it'd be interesting. it also spaces it slightly with actual spaces.. unlike the us release.

### CODE REVIEW

**Comment by mrjnumber1** [comment]
huh whoops.. sorry for that messy automerge in there.. i didnt realize it was part of the PR until just now.

**Comment by Dessyreqt** [comment]
This will probably make it in, but I need some time to test it. I'll be pretty busy this weekend, so I wouldn't expect a merge on this until at least next week.

**Comment by mrjnumber1** [comment]
neato! i didnt try it with every item nor with every symbol i dropped in for, i just tested that the output was the proper bytes and did an edit in a hex editor to sample it out. either way, my favorite part of the randomizer so far is definitely the zora going "hey link, heres some random item!"

**Comment by Dessyreqt** [comment]
This has been pulled in, though I changed what most of the items say.

**Pull request closed without merging**
