### PR TITLE
adding support for v7 rom

### PR DESCRIPTION
**Pull request by sporchia**
Added shuffling for:
1. Swords
2. Pendants
3. Crystals

Added boss hearts into item pool

Added in uncle text

Added in 1/2 or 1/4 magic

fixed some logic based on Christos’ notes

### CODE REVIEW

**Comment by Radagast81** [comment]
Hi Sporchia,
tested your version of the randomizer for a bit and must say: great work!

But there are a few minor issues i want to tell you. First of all i can't see the crystals, regardless of what I do there are allways the pendants showing in the menu bar. And the sprites of the lumberjack tree are a little bugged. (Perhaps my emulator is the course - i'm playin on a retropie with the lr-snes9x-next emulator.)
Other things i have to mention is that some of the changes of v6 are not included in your version of the rom:
- The sanctuary priest is now immortal and also refills your magic.
- The old man on Death Mountain also refills your magic.
- The 3 pots in Link’s house have been changed from hearts to a full magic jar and 2 faeries.
Idk if there are other changes/bugfixes of v6 that are missing. Other than this great work and thanks for removing all the textboxes really nice and fast to play without them...

**Comment by sporchia** [comment]
the v7 rom is maintained upstream and has made a few changes that reverted some of the v6 things, such as the magic refill of NPC's and links house. To switch between pendants and crystals while in the HUD I believe you can press the select button, it should always remember whatever you had last.

Thank you for the feed back, and this project is really the work of Dessyreqt, so all praise should really go that way. :) I just made a patch that updated a few of the things for v7 rom.

**Comment by Radagast81** [comment]
Didn't know the rom is maintained somewhere else, so everything is fine! Thanks for the tip with the select button - worked for me. (Perhaps add this in the faq for v7...)
And also with the sprites of the lumberjack tree - in the next seed there wasn't an issue with this. I'll keep track of this and let all of you notice when i identify the reason for this bugg.

**Comment by Dessyreqt** [comment]
There has been an update to the master branch. Please double check if anything from this branch didn't get implemented in the master.

**Comment by sporchia** [comment]
I think if you use L2Sword anywhere other than pedestal it will crash, will want to use the new MasterSword (0x50) Item

**Comment by KatDevsGames** [comment]
Pedestal should use 0x01, all other locations should use 0x50.

**Comment by Dessyreqt** [comment]
That has been implemented. Is there anything else?

**Comment by KatDevsGames** [comment]
It looks all addressed except for the lumberjack sprites issue which I have yet to encounter in a supported platform (regular snes9x, bsnes/higan, or sd2snes). Nothing relating to these sprites has been changed so I'm less sure as to the cause. Can anyone get steps reproduce this on bsnes (if possible)? That would be the best way to learn more.

**Comment by Radagast81** [comment]
hey mmxbass,
couldn't reproduce the issues with the sprites myself so it's only seems to happen on special situations. Though i'd say it's nothing to worry about unless more information under which circumstances this happens could be get. It doesn't effekt the gameplay so it's anyway very low priority...
I think you can leave this comment of mine and close the corresponding issue on the rom-project.

**Pull request closed without merging**
